/**
 * Generated from contracts/agentera-cloud.openapi.yaml.
 * Contract SHA-256: 9879b3dad6f287f0fd9209e4f80669d09f88a4be5419b8f01de05a8af3033eae
 * Do not edit this file directly.
 */

export type paths = {
  readonly "/.well-known/agentera-signing-keys.json": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["getAgentEraSigningKeys"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/deletion": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["requestAccountDeletion"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/deletion/recover": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["recoverAccountDeletion"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/identities/{kind}": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete: operations["removeAccountIdentity"];
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/identities/bind": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["bindAccountIdentity"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/me": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["getAccountProfile"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/password/change": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["changeAccountPassword"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/password/reset": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["resetAccountPassword"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/register": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["registerAccount"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/agent-definitions": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["listUserAgentDefinitions"];
    readonly put?: never;
    /** @description The maximum agent publication request body is 2621440 bytes. Drafts remain local and are not accepted by this API. */
    readonly post: operations["publishInitialUserAgentVersion"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/agent-definitions/{definition_id}": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["getUserAgentDefinition"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/agent-definitions/{definition_id}/versions": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["listUserAgentVersions"];
    readonly put?: never;
    /** @description The maximum agent publication request body is 2621440 bytes. A base version provides optimistic concurrency. */
    readonly post: operations["publishNextUserAgentVersion"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/agent-installations": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /** @description The maximum Agent metadata request body is 65536 bytes. The authenticated device determines installation ownership. */
    readonly post: operations["createUserAgentInstallation"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/agent-installations/{installation_id}/activate": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /** @description The maximum Agent metadata request body is 65536 bytes. Device proof binds the signed version digest to one local Runtime profile. */
    readonly post: operations["activateUserAgentInstallation"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/agent-installations/{installation_id}/archive": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /** @description The maximum Agent metadata request body is 65536 bytes. Archive changes cloud control metadata only and does not delete a Hermes profile. */
    readonly post: operations["archiveUserAgentInstallation"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/agent-installations/{installation_id}/select-version": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /** @description The maximum Agent metadata request body is 65536 bytes. A newly selected version applies only to later Runtime bindings. */
    readonly post: operations["selectUserAgentInstallationVersion"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/agent-versions/{version_id}": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["getUserAgentVersion"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/agent-versions/{version_id}/revocations": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /** @description The maximum Agent metadata request body is 65536 bytes. Revocation is append-only and never mutates an immutable version. */
    readonly post: operations["revokeUserAgentVersion"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/browser/login": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["browserLogin"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/browser/logout": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["browserLogout"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/devices": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["listDevices"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/devices/{device_id}": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete: operations["revokeDevice"];
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/devices/current/logout": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["logoutCurrentDevice"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/devices/self-revoke": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["selfRevokeDevice"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/legal/current": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["getCurrentLegalDocuments"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/oauth/authorize/approve": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["approveDesktopAuthorization"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/oauth/refresh": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["refreshDesktopSession"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/oauth/revoke": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["revokeDesktopSession"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/oauth/token": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["exchangeDesktopAuthorizationCode"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/runtime-binding-records": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /** @description The maximum Agent metadata request body is 65536 bytes. This records immutable control-plane identifiers and never uploads session, Memory, files, or credentials. */
    readonly post: operations["recordUserAgentRuntimeBinding"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/verification/challenges": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["createVerificationChallenge"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/verification/challenges/verify": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["verifyIdentityChallenge"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/oauth/authorize": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["beginDesktopAuthorization"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    readonly AccountDeletionRecoveryRequest: {
      readonly identity: string;
      readonly password: string;
      readonly verification_receipt: string;
    };
    readonly AccountDeletionRequest: {
      readonly current_password: string;
      readonly verification_receipt: string;
    };
    readonly AccountProfile: {
      readonly identity_kinds: readonly components["schemas"]["IdentityKind"][];
      readonly nickname?: string;
      /** Format: uuid */
      readonly personal_space_id: string;
      /** @constant */
      readonly status: "active";
      /** Format: uuid */
      readonly user_id: string;
    };
    readonly ActivateAgentInstallationRequest: {
      /** @description Ed25519 activation signature encoded as canonical unpadded base64url. */
      readonly device_proof: string;
      /** Format: uuid */
      readonly runtime_profile_id: string;
      /** Format: int64 */
      readonly timestamp: number;
      readonly version_digest: components["schemas"]["SHA256Digest"];
    };
    readonly AgentBundleAssetV1: {
      readonly content: string;
      readonly path: string;
    };
    readonly AgentDefinition: {
      /** Format: date-time */
      readonly created_at: string;
      readonly display_name: string;
      /** @description Static icon bytes encoded as canonical unpadded base64url. */
      readonly icon_data?: string;
      /** @enum {string} */
      readonly icon_media_type?: "image/png" | "image/webp";
      /** Format: uuid */
      readonly id: string;
      /** Format: uuid */
      readonly latest_version_id?: string;
      /** @enum {string} */
      readonly status: "active" | "archived";
      /** Format: date-time */
      readonly updated_at: string;
    };
    readonly AgentDefinitionList: {
      readonly definitions: readonly components["schemas"]["AgentDefinition"][];
    };
    readonly AgentDependencyV1: {
      /** Format: uuid */
      readonly agent_definition_id: string;
      /** Format: uuid */
      readonly agent_version_id: string;
    };
    readonly AgentIdentityV1: {
      readonly system_prompt: string;
    };
    readonly AgentInstallation: {
      /** Format: date-time */
      readonly activated_at?: string;
      /** Format: date-time */
      readonly archived_at?: string;
      /** Format: date-time */
      readonly created_at: string;
      /** Format: uuid */
      readonly definition_id: string;
      /** Format: uuid */
      readonly id: string;
      /** Format: uuid */
      readonly policy_snapshot_id?: string;
      /** Format: uuid */
      readonly runtime_profile_id?: string;
      /** Format: uuid */
      readonly selected_version_id: string;
      /** @enum {string} */
      readonly status: "pending" | "active" | "archived";
      /** @constant */
      readonly update_policy: "manual";
      /** Format: date-time */
      readonly updated_at: string;
    };
    readonly AgentInstallationCreation: {
      readonly installation: components["schemas"]["AgentInstallation"];
      readonly policy_snapshot: components["schemas"]["AgentPolicySnapshot"];
      readonly replayed: boolean;
    };
    readonly AgentManifestAssetV1: {
      /** @enum {string} */
      readonly kind: "skill" | "sop" | "knowledge";
      /** @enum {string} */
      readonly media_type: "text/markdown" | "text/plain";
      readonly path: string;
      readonly sha256: components["schemas"]["SHA256Digest"];
    };
    readonly AgentManifestV1: {
      readonly assets: readonly components["schemas"]["AgentManifestAssetV1"][];
      readonly dependencies: readonly components["schemas"]["AgentDependencyV1"][];
      readonly identity: components["schemas"]["AgentIdentityV1"];
      readonly model_constraints: components["schemas"]["AgentModelConstraintsV1"];
      readonly runtime_compatibility: components["schemas"]["AgentRuntimeCompatibilityV1"];
      /** @constant */
      readonly schema_version: 1;
      readonly tools: components["schemas"]["AgentToolPolicyV1"];
    };
    readonly AgentModelConstraintsV1: {
      readonly allowed_models: readonly string[];
      readonly allowed_providers: readonly string[];
    };
    readonly AgentPolicyDocumentV1: {
      /** Format: uuid */
      readonly agent_definition_id: string;
      /** Format: uuid */
      readonly agent_version_id: string;
      readonly deny_rules: readonly string[];
      readonly model_constraints: components["schemas"]["AgentModelConstraintsV1"];
      /** @constant */
      readonly publication_allowed: false;
      readonly runtime_compatibility: components["schemas"]["AgentRuntimeCompatibilityV1"];
      /** @constant */
      readonly schema_version: 1;
      readonly tools: components["schemas"]["AgentToolPolicyV1"];
      readonly version_digest: components["schemas"]["SHA256Digest"];
    };
    readonly AgentPolicySnapshot: {
      /** Format: uuid */
      readonly agent_version_id: string;
      readonly content_digest: components["schemas"]["SHA256Digest"];
      /** Format: date-time */
      readonly created_at: string;
      readonly document: components["schemas"]["AgentPolicyDocumentV1"];
      /** Format: uuid */
      readonly id: string;
      /** Format: uuid */
      readonly installation_id: string;
      /** Format: uri */
      readonly issuer: string;
      /** Format: int64 */
      readonly policy_version: number;
      /** @description Ed25519 agent_policy signature encoded as canonical unpadded base64url. */
      readonly signature: string;
      readonly signing_key_id: string;
    };
    readonly AgentPublication: {
      readonly definition: components["schemas"]["AgentDefinition"];
      readonly replayed: boolean;
      readonly version: components["schemas"]["AgentVersion"];
    };
    readonly AgentRuntimeCompatibilityV1: {
      readonly maximum_version_exclusive?: string | null;
      readonly minimum_version: string;
    };
    readonly AgentToolPolicyV1: {
      readonly allowed: readonly string[];
      readonly denied: readonly string[];
    };
    readonly AgentVersion: {
      readonly bundle: components["schemas"]["AgentVersionBundleV1"];
      readonly content_digest: components["schemas"]["SHA256Digest"];
      /** Format: uuid */
      readonly definition_id: string;
      /** Format: uuid */
      readonly id: string;
      readonly manifest: components["schemas"]["AgentManifestV1"];
      /** Format: date-time */
      readonly published_at: string;
      readonly runtime_maximum_version_exclusive?: string;
      readonly runtime_minimum_version: string;
      /** @description Ed25519 agent_version signature encoded as canonical unpadded base64url. */
      readonly signature: string;
      readonly signing_key_id: string;
      /** Format: int64 */
      readonly version_number: number;
    };
    readonly AgentVersionBundleV1: {
      readonly assets: readonly components["schemas"]["AgentBundleAssetV1"][];
    };
    readonly AgentVersionList: {
      readonly versions: readonly components["schemas"]["AgentVersion"][];
    };
    readonly AgentVersionRevocation: {
      /** Format: date-time */
      readonly created_at: string;
      /** Format: uuid */
      readonly id: string;
      /** Format: uuid */
      readonly policy_snapshot_id: string;
      readonly reason_code: string;
      readonly replayed: boolean;
      /** Format: uuid */
      readonly superseding_version_id?: string;
      /** Format: uuid */
      readonly version_id: string;
    };
    readonly ArchiveAgentInstallationRequest: Record<string, never>;
    readonly AuthorizationApprovalRequest: {
      /** Format: uuid */
      readonly request_id: string;
    };
    readonly AuthorizationApprovalResponse: {
      /** Format: uri */
      readonly redirect_uri: string;
    };
    readonly AuthorizationCodeExchangeRequest: {
      readonly authorization_code: string;
      readonly code_verifier: string;
      /** @description Ed25519 signature over the documented device-proof digest, encoded as unpadded base64url. */
      readonly device_proof: string;
      /** Format: uuid */
      readonly installation_id: string;
    };
    readonly BrowserLoginRequest: {
      readonly identity: string;
      readonly password: string;
    };
    readonly BrowserLoginResponse: {
      readonly csrf_token: string;
      readonly nickname?: string;
      /** Format: uuid */
      readonly personal_space_id: string;
      /** Format: uuid */
      readonly user_id: string;
    };
    readonly CreateAgentInstallationRequest: {
      /** Format: uuid */
      readonly definition_id: string;
      /** Format: uuid */
      readonly version_id: string;
    };
    readonly CreateRuntimeBindingRecordRequest: {
      /** Format: uuid */
      readonly agent_installation_id: string;
      /** Format: uuid */
      readonly agent_version_id: string;
      /** Format: uuid */
      readonly binding_id: string;
      /** Format: uuid */
      readonly policy_snapshot_id: string;
      /** Format: uuid */
      readonly runtime_profile_id: string;
      readonly runtime_version: string;
      readonly tool_permission_digest: components["schemas"]["SHA256Digest"];
    };
    readonly CurrentLegalDocuments: {
      readonly privacy_version: string;
      readonly terms_version: string;
    };
    readonly CurrentPasswordRequest: {
      readonly current_password: string;
    };
    readonly Device: {
      readonly app_version: string;
      readonly current: boolean;
      /** Format: uuid */
      readonly device_id: string;
      readonly display_name: string;
      /** Format: date-time */
      readonly last_seen_at: string;
      /** @enum {string} */
      readonly platform: "darwin" | "windows" | "linux";
      /** @enum {string} */
      readonly status: "active" | "inactive" | "revoked";
    };
    readonly DeviceList: {
      readonly devices: readonly components["schemas"]["Device"][];
    };
    readonly DeviceSelfRevokeRequest: {
      /** Format: uuid */
      readonly device_id: string;
      /** Format: uuid */
      readonly installation_id: string;
      /** @description 32 random bytes encoded as canonical unpadded base64url. */
      readonly nonce: string;
      /** @description Ed25519 signature of the AgentEra self-revocation digest, encoded as canonical unpadded base64url. */
      readonly signature: string;
      /** Format: int64 */
      readonly timestamp: number;
    };
    /** @enum {string} */
    readonly ErrorCode:
      | "invalid_request"
      | "verification_required"
      | "identity_conflict"
      | "invalid_credentials"
      | "device_limit_reached"
      | "authorization_expired"
      | "authorization_replayed"
      | "session_revoked"
      | "account_pending_deletion"
      | "account_disabled"
      | "last_identity"
      | "deletion_window_expired"
      | "account_not_found"
      | "device_not_found"
      | "self_revoke_replayed"
      | "invalid_agent_content"
      | "runtime_incompatible"
      | "invalid_device_proof"
      | "not_found"
      | "version_conflict"
      | "idempotency_conflict"
      | "definition_archived"
      | "version_revoked"
      | "activation_conflict"
      | "installation_archived"
      | "service_unavailable";
    readonly ErrorEnvelope: {
      readonly error: {
        readonly code: components["schemas"]["ErrorCode"];
        /** @constant */
        readonly message: "localized by the client";
        /** Format: uuid */
        readonly request_id: string;
      };
    };
    readonly IdentityBindingRequest: {
      readonly current_password: string;
      readonly verification_receipt: string;
    };
    /** @enum {string} */
    readonly IdentityKind: "email" | "phone";
    readonly PasswordChangeRequest: {
      readonly current_password: string;
      readonly new_password: string;
    };
    readonly PasswordResetRequest: {
      readonly new_password: string;
      readonly verification_receipt: string;
    };
    readonly PublishInitialAgentRequest: {
      readonly bundle: components["schemas"]["AgentVersionBundleV1"];
      readonly display_name: string;
      /** @description Static icon bytes encoded as canonical unpadded base64url. */
      readonly icon_data?: string;
      /** @enum {string} */
      readonly icon_media_type?: "image/png" | "image/webp";
      readonly manifest: components["schemas"]["AgentManifestV1"];
    };
    readonly PublishNextAgentVersionRequest: {
      /** Format: uuid */
      readonly base_version_id: string;
      readonly bundle: components["schemas"]["AgentVersionBundleV1"];
      readonly manifest: components["schemas"]["AgentManifestV1"];
    };
    readonly RefreshTokenRequest: {
      readonly refresh_token: string;
    };
    readonly RegisterAccountRequest: {
      readonly kind: components["schemas"]["IdentityKind"];
      readonly nickname?: string;
      readonly password: string;
      readonly privacy_version: string;
      readonly terms_version: string;
      readonly verification_receipt: string;
    };
    readonly Registration: {
      /** Format: uuid */
      readonly personal_space_id: string;
      /** Format: uuid */
      readonly user_id: string;
    };
    readonly RevokeAgentVersionRequest: {
      /** Format: uuid */
      readonly policy_snapshot_id: string;
      readonly reason_code: string;
      /** Format: uuid */
      readonly superseding_version_id?: string;
    };
    readonly RuntimeBindingRecord: {
      /** Format: uuid */
      readonly agent_installation_id: string;
      /** Format: uuid */
      readonly agent_version_id: string;
      /** Format: date-time */
      readonly created_at: string;
      /** Format: uuid */
      readonly id: string;
      /** Format: uuid */
      readonly policy_snapshot_id: string;
      /** Format: uuid */
      readonly runtime_profile_id: string;
      readonly runtime_version: string;
      readonly tool_permission_digest: components["schemas"]["SHA256Digest"];
    };
    readonly SelectAgentInstallationVersionRequest: {
      /** Format: uuid */
      readonly version_id: string;
    };
    /** @description Lowercase hexadecimal SHA-256 digest. */
    readonly SHA256Digest: string;
    readonly SigningKey: {
      /** @constant */
      readonly alg: "EdDSA";
      /** @constant */
      readonly crv: "Ed25519";
      readonly kid: string;
      /** @constant */
      readonly kty: "OKP";
      /** @enum {string} */
      readonly purpose:
        | "access"
        | "offline_entitlement"
        | "agent_version"
        | "agent_policy";
      /** @constant */
      readonly use: "sig";
      readonly x: string;
    };
    readonly SigningKeySet: {
      readonly keys: readonly components["schemas"]["SigningKey"][];
    };
    readonly TokenResponse: {
      /** Format: date-time */
      readonly access_expires_at: string;
      readonly access_token: string;
      /** Format: uuid */
      readonly device_id: string;
      readonly offline_entitlement: string;
      /** Format: date-time */
      readonly offline_expires_at: string;
      /** Format: uuid */
      readonly personal_space_id: string;
      /** Format: date-time */
      readonly refresh_expires_at: string;
      readonly refresh_token: string;
      /** Format: uuid */
      readonly user_id: string;
    };
    readonly VerificationChallengeRequest: {
      readonly captcha_token?: string;
      readonly destination: string;
      readonly kind: components["schemas"]["IdentityKind"];
      readonly purpose: components["schemas"]["VerificationPurpose"];
    };
    readonly VerificationCodeRequest: {
      readonly code: string;
      readonly destination: string;
      readonly kind: components["schemas"]["IdentityKind"];
      readonly purpose: components["schemas"]["VerificationPurpose"];
    };
    /** @enum {string} */
    readonly VerificationPurpose:
      | "registration"
      | "password_reset"
      | "bind_identity"
      | "account_deletion"
      | "deletion_recovery";
    readonly VerificationReceipt: {
      /** Format: date-time */
      readonly expires_at: string;
      readonly receipt: string;
      /** @constant */
      readonly status: "verified";
    };
  };
  responses: {
    /** @description The account is disabled or pending deletion. */
    readonly AccountUnavailable: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description The Agent version, installation, revocation, or idempotency state conflicts with the request. */
    readonly AgentConflict: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description The USER-owned Agent object is absent or outside the authenticated owner boundary. */
    readonly AgentNotFound: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description The verified identity belongs to another account. */
    readonly IdentityConflict: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Identity and password do not authenticate an active account. */
    readonly InvalidCredentials: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description The request or verification receipt is invalid. */
    readonly InvalidRequest: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description A required account service is temporarily unavailable. */
    readonly ServiceUnavailable: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description The browser session is absent, expired, or revoked. */
    readonly SessionRevoked: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
  };
  parameters: {
    readonly AgentDefinitionID: string;
    readonly AgentInstallationID: string;
    readonly AgentVersionID: string;
    readonly CSRFToken: string;
    /** @description Opaque operation key. The same key may be replayed only with the exact same request. */
    readonly IdempotencyKey: string;
    /** @description Required when browserSession is used; omitted for desktopAccessToken. */
    readonly OptionalCSRFToken: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
  readonly getAgentEraSigningKeys: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Public Ed25519 access and offline-entitlement verification keys. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["SigningKeySet"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly requestAccountDeletion: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        readonly "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["AccountDeletionRequest"];
      };
    };
    readonly responses: {
      /** @description Account entered pending deletion and all cloud sessions, devices, and offline entitlements were revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["InvalidCredentials"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly recoverAccountDeletion: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["AccountDeletionRecoveryRequest"];
      };
    };
    readonly responses: {
      /** @description Pending deletion recovered within seven days; old device sessions stay revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["InvalidCredentials"];
      /** @description The seven-day recovery window expired. */
      readonly 410: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly removeAccountIdentity: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        readonly "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      readonly path: {
        readonly kind: components["schemas"]["IdentityKind"];
      };
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["CurrentPasswordRequest"];
      };
    };
    readonly responses: {
      /** @description Secondary login identity removed. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["InvalidCredentials"];
      /** @description The only remaining login identity cannot be removed. */
      readonly 409: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly bindAccountIdentity: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        readonly "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["IdentityBindingRequest"];
      };
    };
    readonly responses: {
      /** @description Verified secondary identity bound after password reauthentication. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["InvalidCredentials"];
      readonly 409: components["responses"]["IdentityConflict"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly getAccountProfile: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Account and identity-kind metadata without email or phone values. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AccountProfile"];
        };
      };
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 404: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly changeAccountPassword: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["PasswordChangeRequest"];
      };
    };
    readonly responses: {
      /** @description Password changed; the calling product session is preserved and every other device is revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly resetAccountPassword: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["PasswordResetRequest"];
      };
    };
    readonly responses: {
      /** @description Password replaced and every existing device session family revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly registerAccount: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["RegisterAccountRequest"];
      };
    };
    readonly responses: {
      /** @description User and personal space created atomically. */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["Registration"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 409: components["responses"]["IdentityConflict"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly listUserAgentDefinitions: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description USER-owned Agent definitions visible to the authenticated product principal. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AgentDefinitionList"];
        };
      };
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly publishInitialUserAgentVersion: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        /** @description Opaque operation key. The same key may be replayed only with the exact same request. */
        readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["PublishInitialAgentRequest"];
      };
    };
    readonly responses: {
      /** @description Definition and immutable first version published atomically. */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AgentPublication"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 409: components["responses"]["AgentConflict"];
      readonly 413: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly getUserAgentDefinition: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        readonly definition_id: components["parameters"]["AgentDefinitionID"];
      };
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description One USER-owned Agent definition. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AgentDefinition"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 404: components["responses"]["AgentNotFound"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly listUserAgentVersions: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        readonly definition_id: components["parameters"]["AgentDefinitionID"];
      };
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Immutable versions for one USER-owned Agent definition. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AgentVersionList"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 404: components["responses"]["AgentNotFound"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly publishNextUserAgentVersion: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        /** @description Opaque operation key. The same key may be replayed only with the exact same request. */
        readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      readonly path: {
        readonly definition_id: components["parameters"]["AgentDefinitionID"];
      };
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["PublishNextAgentVersionRequest"];
      };
    };
    readonly responses: {
      /** @description Immutable next version published and selected as latest. */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AgentPublication"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 404: components["responses"]["AgentNotFound"];
      readonly 409: components["responses"]["AgentConflict"];
      readonly 413: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly createUserAgentInstallation: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        /** @description Opaque operation key. The same key may be replayed only with the exact same request. */
        readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["CreateAgentInstallationRequest"];
      };
    };
    readonly responses: {
      /** @description Pending installation and signed policy snapshot created atomically. */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AgentInstallationCreation"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 404: components["responses"]["AgentNotFound"];
      readonly 409: components["responses"]["AgentConflict"];
      readonly 413: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly activateUserAgentInstallation: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        /** @description Opaque operation key. The same key may be replayed only with the exact same request. */
        readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      readonly path: {
        readonly installation_id: components["parameters"]["AgentInstallationID"];
      };
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["ActivateAgentInstallationRequest"];
      };
    };
    readonly responses: {
      /** @description Installation activated or an exact activation replay returned. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AgentInstallation"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 404: components["responses"]["AgentNotFound"];
      readonly 409: components["responses"]["AgentConflict"];
      readonly 413: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly archiveUserAgentInstallation: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        /** @description Opaque operation key. The same key may be replayed only with the exact same request. */
        readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      readonly path: {
        readonly installation_id: components["parameters"]["AgentInstallationID"];
      };
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["ArchiveAgentInstallationRequest"];
      };
    };
    readonly responses: {
      /** @description Installation archived without deleting local runtime state. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AgentInstallation"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 404: components["responses"]["AgentNotFound"];
      readonly 409: components["responses"]["AgentConflict"];
      readonly 413: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly selectUserAgentInstallationVersion: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        /** @description Opaque operation key. The same key may be replayed only with the exact same request. */
        readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      readonly path: {
        readonly installation_id: components["parameters"]["AgentInstallationID"];
      };
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["SelectAgentInstallationVersionRequest"];
      };
    };
    readonly responses: {
      /** @description Installation selected version and signed policy snapshot updated atomically. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AgentInstallation"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 404: components["responses"]["AgentNotFound"];
      readonly 409: components["responses"]["AgentConflict"];
      readonly 413: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly getUserAgentVersion: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        readonly version_id: components["parameters"]["AgentVersionID"];
      };
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Signed immutable Agent version and public version assets. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AgentVersion"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 404: components["responses"]["AgentNotFound"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly revokeUserAgentVersion: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        /** @description Opaque operation key. The same key may be replayed only with the exact same request. */
        readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      readonly path: {
        readonly version_id: components["parameters"]["AgentVersionID"];
      };
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["RevokeAgentVersionRequest"];
      };
    };
    readonly responses: {
      /** @description Version revocation appended. */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AgentVersionRevocation"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 404: components["responses"]["AgentNotFound"];
      readonly 409: components["responses"]["AgentConflict"];
      readonly 413: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly browserLogin: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["BrowserLoginRequest"];
      };
    };
    readonly responses: {
      /** @description Host-only browser session started. */
      readonly 200: {
        headers: {
          /** @description HttpOnly, SameSite=Lax browser session cookie; Secure outside loopback development. */
          readonly "Set-Cookie"?: string;
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["BrowserLoginResponse"];
        };
      };
      readonly 401: components["responses"]["InvalidCredentials"];
      readonly 403: components["responses"]["AccountUnavailable"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly browserLogout: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        readonly "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Browser session ended. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 403: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly listDevices: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Redacted active-device list without installation IDs or public keys. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["DeviceList"];
        };
      };
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly revokeDevice: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: {
        /** @description Required when browserSession is used; omitted for desktopAccessToken. */
        readonly "X-CSRF-Token"?: components["parameters"]["OptionalCSRFToken"];
      };
      readonly path: {
        readonly device_id: string;
      };
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Device and its cloud sessions and offline entitlements revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      /** @description Device is not owned by the account or does not exist. */
      readonly 404: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly logoutCurrentDevice: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Calling device and all of its product sessions revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly selfRevokeDevice: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["DeviceSelfRevokeRequest"];
      };
    };
    readonly responses: {
      /** @description Device revoked after Ed25519 proof, nonce, and timestamp validation. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      /** @description Signed device target is unavailable. */
      readonly 404: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Self-revocation nonce was already consumed. */
      readonly 409: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly getCurrentLegalDocuments: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Versions that must be accepted for a new registration. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["CurrentLegalDocuments"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly approveDesktopAuthorization: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        readonly "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["AuthorizationApprovalRequest"];
      };
    };
    readonly responses: {
      /** @description Exact loopback callback URL containing a one-time code and the original state. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AuthorizationApprovalResponse"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 403: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly refreshDesktopSession: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["RefreshTokenRequest"];
      };
    };
    readonly responses: {
      /** @description Rotated refresh token, short-lived access token, and renewed offline entitlement. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["TokenResponse"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 403: components["responses"]["AccountUnavailable"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly revokeDesktopSession: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["RefreshTokenRequest"];
      };
    };
    readonly responses: {
      /** @description The refresh-token family was revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly exchangeDesktopAuthorizationCode: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["AuthorizationCodeExchangeRequest"];
      };
    };
    readonly responses: {
      /** @description Device-bound product session and a new seven-day offline entitlement. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["TokenResponse"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      /** @description The code was replayed or the five-active-device limit was reached. */
      readonly 409: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly recordUserAgentRuntimeBinding: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        /** @description Opaque operation key. The same key may be replayed only with the exact same request. */
        readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["CreateRuntimeBindingRecordRequest"];
      };
    };
    readonly responses: {
      /** @description Runtime binding record persisted for a newly starting session. */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["RuntimeBindingRecord"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 404: components["responses"]["AgentNotFound"];
      readonly 409: components["responses"]["AgentConflict"];
      readonly 413: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly createVerificationChallenge: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["VerificationChallengeRequest"];
      };
    };
    readonly responses: {
      /** @description Delivery accepted without disclosing account existence. */
      readonly 202: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly verifyIdentityChallenge: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["VerificationCodeRequest"];
      };
    };
    readonly responses: {
      /** @description Short-lived, single-use verification receipt. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["VerificationReceipt"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly beginDesktopAuthorization: {
    readonly parameters: {
      readonly query: {
        readonly app_version: string;
        readonly client_id: "agentera-studio";
        readonly code_challenge: string;
        readonly code_challenge_method: "S256";
        readonly device_name: string;
        /** @description Raw Ed25519 public key encoded as unpadded base64url. */
        readonly device_public_key: string;
        readonly installation_id: string;
        readonly platform: "darwin" | "windows" | "linux";
        /** @description Forces explicit browser account authentication when switching desktop users. */
        readonly prompt?: "select_account";
        readonly redirect_uri: string;
        readonly state: string;
      };
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Sensitive request values were persisted and removed from the browser URL. */
      readonly 303: {
        headers: {
          readonly Location: string;
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
}
