/**
 * Generated from contracts/agentera-cloud.openapi.yaml.
 * Contract SHA-256: 1b8f0021be474ba84bff7fc519858dc6533901844f4d70535878950826ec1193
 * Do not edit this file directly.
 */

export type paths = {
  readonly "/.well-known/agentera-signing-keys.json": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["getAgentEraSigningKeys"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/deletion": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["requestAccountDeletion"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/deletion/recover": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["recoverAccountDeletion"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/identities/{kind}": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete: operations["removeAccountIdentity"];
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/identities/bind": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["bindAccountIdentity"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/me": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["getAccountProfile"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/password/change": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["changeAccountPassword"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/password/reset": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["resetAccountPassword"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/accounts/register": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["registerAccount"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/browser/login": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["browserLogin"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/browser/logout": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["browserLogout"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/devices": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["listDevices"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/devices/{device_id}": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete: operations["revokeDevice"];
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/devices/current/logout": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["logoutCurrentDevice"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/devices/self-revoke": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["selfRevokeDevice"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/legal/current": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["getCurrentLegalDocuments"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/oauth/authorize/approve": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["approveDesktopAuthorization"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/oauth/refresh": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["refreshDesktopSession"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/oauth/revoke": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["revokeDesktopSession"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/oauth/token": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["exchangeDesktopAuthorizationCode"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/verification/challenges": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["createVerificationChallenge"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/api/v1/verification/challenges/verify": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post: operations["verifyIdentityChallenge"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/oauth/authorize": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get: operations["beginDesktopAuthorization"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    readonly AccountDeletionRecoveryRequest: {
      readonly identity: string;
      readonly password: string;
      readonly verification_receipt: string;
    };
    readonly AccountDeletionRequest: {
      readonly current_password: string;
      readonly verification_receipt: string;
    };
    readonly AccountProfile: {
      readonly identity_kinds: readonly components["schemas"]["IdentityKind"][];
      readonly nickname?: string;
      /** Format: uuid */
      readonly personal_space_id: string;
      /** @constant */
      readonly status: "active";
      /** Format: uuid */
      readonly user_id: string;
    };
    readonly AuthorizationApprovalRequest: {
      /** Format: uuid */
      readonly request_id: string;
    };
    readonly AuthorizationApprovalResponse: {
      /** Format: uri */
      readonly redirect_uri: string;
    };
    readonly AuthorizationCodeExchangeRequest: {
      readonly authorization_code: string;
      readonly code_verifier: string;
      /** @description Ed25519 signature over the documented device-proof digest, encoded as unpadded base64url. */
      readonly device_proof: string;
      /** Format: uuid */
      readonly installation_id: string;
    };
    readonly BrowserLoginRequest: {
      readonly identity: string;
      readonly password: string;
    };
    readonly BrowserLoginResponse: {
      readonly csrf_token: string;
      readonly nickname?: string;
      /** Format: uuid */
      readonly personal_space_id: string;
      /** Format: uuid */
      readonly user_id: string;
    };
    readonly CurrentLegalDocuments: {
      readonly privacy_version: string;
      readonly terms_version: string;
    };
    readonly CurrentPasswordRequest: {
      readonly current_password: string;
    };
    readonly Device: {
      readonly app_version: string;
      readonly current: boolean;
      /** Format: uuid */
      readonly device_id: string;
      readonly display_name: string;
      /** Format: date-time */
      readonly last_seen_at: string;
      /** @enum {string} */
      readonly platform: "darwin" | "windows" | "linux";
      /** @enum {string} */
      readonly status: "active" | "inactive" | "revoked";
    };
    readonly DeviceList: {
      readonly devices: readonly components["schemas"]["Device"][];
    };
    readonly DeviceSelfRevokeRequest: {
      /** Format: uuid */
      readonly device_id: string;
      /** Format: uuid */
      readonly installation_id: string;
      /** @description 32 random bytes encoded as canonical unpadded base64url. */
      readonly nonce: string;
      /** @description Ed25519 signature of the AgentEra self-revocation digest, encoded as canonical unpadded base64url. */
      readonly signature: string;
      /** Format: int64 */
      readonly timestamp: number;
    };
    /** @enum {string} */
    readonly ErrorCode:
      | "invalid_request"
      | "verification_required"
      | "identity_conflict"
      | "invalid_credentials"
      | "device_limit_reached"
      | "authorization_expired"
      | "authorization_replayed"
      | "session_revoked"
      | "account_pending_deletion"
      | "account_disabled"
      | "last_identity"
      | "deletion_window_expired"
      | "account_not_found"
      | "device_not_found"
      | "self_revoke_replayed"
      | "service_unavailable";
    readonly ErrorEnvelope: {
      readonly error: {
        readonly code: components["schemas"]["ErrorCode"];
        /** @constant */
        readonly message: "localized by the client";
        /** Format: uuid */
        readonly request_id: string;
      };
    };
    readonly IdentityBindingRequest: {
      readonly current_password: string;
      readonly verification_receipt: string;
    };
    /** @enum {string} */
    readonly IdentityKind: "email" | "phone";
    readonly PasswordChangeRequest: {
      readonly current_password: string;
      readonly new_password: string;
    };
    readonly PasswordResetRequest: {
      readonly new_password: string;
      readonly verification_receipt: string;
    };
    readonly RefreshTokenRequest: {
      readonly refresh_token: string;
    };
    readonly RegisterAccountRequest: {
      readonly kind: components["schemas"]["IdentityKind"];
      readonly nickname?: string;
      readonly password: string;
      readonly privacy_version: string;
      readonly terms_version: string;
      readonly verification_receipt: string;
    };
    readonly Registration: {
      /** Format: uuid */
      readonly personal_space_id: string;
      /** Format: uuid */
      readonly user_id: string;
    };
    readonly SigningKey: {
      /** @constant */
      readonly alg: "EdDSA";
      /** @constant */
      readonly crv: "Ed25519";
      readonly kid: string;
      /** @constant */
      readonly kty: "OKP";
      /** @enum {string} */
      readonly purpose: "access" | "offline_entitlement";
      /** @constant */
      readonly use: "sig";
      readonly x: string;
    };
    readonly SigningKeySet: {
      readonly keys: readonly components["schemas"]["SigningKey"][];
    };
    readonly TokenResponse: {
      /** Format: date-time */
      readonly access_expires_at: string;
      readonly access_token: string;
      /** Format: uuid */
      readonly device_id: string;
      readonly offline_entitlement: string;
      /** Format: date-time */
      readonly offline_expires_at: string;
      /** Format: uuid */
      readonly personal_space_id: string;
      /** Format: date-time */
      readonly refresh_expires_at: string;
      readonly refresh_token: string;
      /** Format: uuid */
      readonly user_id: string;
    };
    readonly VerificationChallengeRequest: {
      readonly captcha_token?: string;
      readonly destination: string;
      readonly kind: components["schemas"]["IdentityKind"];
      readonly purpose: components["schemas"]["VerificationPurpose"];
    };
    readonly VerificationCodeRequest: {
      readonly code: string;
      readonly destination: string;
      readonly kind: components["schemas"]["IdentityKind"];
      readonly purpose: components["schemas"]["VerificationPurpose"];
    };
    /** @enum {string} */
    readonly VerificationPurpose:
      | "registration"
      | "password_reset"
      | "bind_identity"
      | "account_deletion"
      | "deletion_recovery";
    readonly VerificationReceipt: {
      /** Format: date-time */
      readonly expires_at: string;
      readonly receipt: string;
      /** @constant */
      readonly status: "verified";
    };
  };
  responses: {
    /** @description The account is disabled or pending deletion. */
    readonly AccountUnavailable: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description The verified identity belongs to another account. */
    readonly IdentityConflict: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Identity and password do not authenticate an active account. */
    readonly InvalidCredentials: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description The request or verification receipt is invalid. */
    readonly InvalidRequest: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description A required account service is temporarily unavailable. */
    readonly ServiceUnavailable: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description The browser session is absent, expired, or revoked. */
    readonly SessionRevoked: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
  };
  parameters: {
    readonly CSRFToken: string;
    /** @description Required when browserSession is used; omitted for desktopAccessToken. */
    readonly OptionalCSRFToken: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
  readonly getAgentEraSigningKeys: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Public Ed25519 access and offline-entitlement verification keys. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["SigningKeySet"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly requestAccountDeletion: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        readonly "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["AccountDeletionRequest"];
      };
    };
    readonly responses: {
      /** @description Account entered pending deletion and all cloud sessions, devices, and offline entitlements were revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["InvalidCredentials"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly recoverAccountDeletion: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["AccountDeletionRecoveryRequest"];
      };
    };
    readonly responses: {
      /** @description Pending deletion recovered within seven days; old device sessions stay revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["InvalidCredentials"];
      /** @description The seven-day recovery window expired. */
      readonly 410: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly removeAccountIdentity: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        readonly "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      readonly path: {
        readonly kind: components["schemas"]["IdentityKind"];
      };
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["CurrentPasswordRequest"];
      };
    };
    readonly responses: {
      /** @description Secondary login identity removed. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["InvalidCredentials"];
      /** @description The only remaining login identity cannot be removed. */
      readonly 409: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly bindAccountIdentity: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        readonly "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["IdentityBindingRequest"];
      };
    };
    readonly responses: {
      /** @description Verified secondary identity bound after password reauthentication. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["InvalidCredentials"];
      readonly 409: components["responses"]["IdentityConflict"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly getAccountProfile: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Account and identity-kind metadata without email or phone values. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AccountProfile"];
        };
      };
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 404: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly changeAccountPassword: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["PasswordChangeRequest"];
      };
    };
    readonly responses: {
      /** @description Password changed; the calling product session is preserved and every other device is revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly resetAccountPassword: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["PasswordResetRequest"];
      };
    };
    readonly responses: {
      /** @description Password replaced and every existing device session family revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly registerAccount: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["RegisterAccountRequest"];
      };
    };
    readonly responses: {
      /** @description User and personal space created atomically. */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["Registration"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 409: components["responses"]["IdentityConflict"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly browserLogin: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["BrowserLoginRequest"];
      };
    };
    readonly responses: {
      /** @description Host-only browser session started. */
      readonly 200: {
        headers: {
          /** @description HttpOnly, SameSite=Lax browser session cookie; Secure outside loopback development. */
          readonly "Set-Cookie"?: string;
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["BrowserLoginResponse"];
        };
      };
      readonly 401: components["responses"]["InvalidCredentials"];
      readonly 403: components["responses"]["AccountUnavailable"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly browserLogout: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        readonly "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Browser session ended. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 403: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly listDevices: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Redacted active-device list without installation IDs or public keys. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["DeviceList"];
        };
      };
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly revokeDevice: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: {
        /** @description Required when browserSession is used; omitted for desktopAccessToken. */
        readonly "X-CSRF-Token"?: components["parameters"]["OptionalCSRFToken"];
      };
      readonly path: {
        readonly device_id: string;
      };
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Device and its cloud sessions and offline entitlements revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      /** @description Device is not owned by the account or does not exist. */
      readonly 404: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly logoutCurrentDevice: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Calling device and all of its product sessions revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly selfRevokeDevice: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["DeviceSelfRevokeRequest"];
      };
    };
    readonly responses: {
      /** @description Device revoked after Ed25519 proof, nonce, and timestamp validation. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      /** @description Signed device target is unavailable. */
      readonly 404: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Self-revocation nonce was already consumed. */
      readonly 409: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly getCurrentLegalDocuments: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Versions that must be accepted for a new registration. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["CurrentLegalDocuments"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly approveDesktopAuthorization: {
    readonly parameters: {
      readonly query?: never;
      readonly header: {
        readonly "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["AuthorizationApprovalRequest"];
      };
    };
    readonly responses: {
      /** @description Exact loopback callback URL containing a one-time code and the original state. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AuthorizationApprovalResponse"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 403: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly refreshDesktopSession: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["RefreshTokenRequest"];
      };
    };
    readonly responses: {
      /** @description Rotated refresh token, short-lived access token, and renewed offline entitlement. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["TokenResponse"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 403: components["responses"]["AccountUnavailable"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly revokeDesktopSession: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["RefreshTokenRequest"];
      };
    };
    readonly responses: {
      /** @description The refresh-token family was revoked. */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 401: components["responses"]["SessionRevoked"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly exchangeDesktopAuthorizationCode: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["AuthorizationCodeExchangeRequest"];
      };
    };
    readonly responses: {
      /** @description Device-bound product session and a new seven-day offline entitlement. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["TokenResponse"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      /** @description The code was replayed or the five-active-device limit was reached. */
      readonly 409: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly createVerificationChallenge: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["VerificationChallengeRequest"];
      };
    };
    readonly responses: {
      /** @description Delivery accepted without disclosing account existence. */
      readonly 202: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly verifyIdentityChallenge: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["VerificationCodeRequest"];
      };
    };
    readonly responses: {
      /** @description Short-lived, single-use verification receipt. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["VerificationReceipt"];
        };
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
  readonly beginDesktopAuthorization: {
    readonly parameters: {
      readonly query: {
        readonly app_version: string;
        readonly client_id: "agentera-studio";
        readonly code_challenge: string;
        readonly code_challenge_method: "S256";
        readonly device_name: string;
        /** @description Raw Ed25519 public key encoded as unpadded base64url. */
        readonly device_public_key: string;
        readonly installation_id: string;
        readonly platform: "darwin" | "windows" | "linux";
        /** @description Forces explicit browser account authentication when switching desktop users. */
        readonly prompt?: "select_account";
        readonly redirect_uri: string;
        readonly state: string;
      };
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Sensitive request values were persisted and removed from the browser URL. */
      readonly 303: {
        headers: {
          readonly Location: string;
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 400: components["responses"]["InvalidRequest"];
      readonly 503: components["responses"]["ServiceUnavailable"];
    };
  };
}
